- name: "Install and configure Chrisley's weather application"
  hosts: meteo2
#  hosts: "{{ target | default('nothing') }}"
  roles:
    - "{{ morpheus['customOptions']['option_ansible_playbook'] }}"
  vars:
    ansible_user: christopher.ley@ibm.com
  become: true
