- name: "Install and configure Chrisley's weather application"
  hosts: all
#  hosts: "{{ target | default('nothing') }}"
  roles:
    - "{{ morpheus['customOptions']['chrisley_ansible_roles'] }}"
  vars:
    ansible_user: christopher.ley@ibm.com
  become: true
