- name: "Install and configure Chrisley's weather application"
  hosts: "{{ morpheus['customOptions']['chrisley_host'] }}"
#  hosts: "{{ target | default('nothing') }}"
  roles:
#    - "{{ morpheus['customOptions']['chrisley_ansible_roles'] }}"
    - weather-chrisley
  vars:
    ansible_user: test
    ansible_ssh_private_key_file: test
  become: true
