- name: "Install and configure Chrisley's weather application"
  hosts: meteo2
#  hosts: "{{ target | default('nothing') }}"
  roles:
    - weather-chrisley
  vars:
    ansible_user: christopher.ley@ibm.com
  become: true
